/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HealthResponse */
    HealthResponse: {
      /** Checks */
      checks: {
        [key: string]: "ok" | "error" | "not_checked";
      };
      /**
       * Service
       * @enum {string}
       */
      service: "agent" | "optimizer";
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "error";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
